import { randomUUID } from "node:crypto";
import type { State, Product } from "./schema";
export function seed(): State {
  const rows: [
    string,
    string,
    string,
    Product["category"],
    Product["unit"],
    number,
    number,
    number,
    number,
    number,
    string,
    string,
  ][] = [
    [
      "p1",
      "Café de especialidad",
      "Blend casa · tueste medio",
      "Cafetería",
      "kg",
      2.4,
      4,
      8,
      1,
      2450,
      "s1",
      "coffee",
    ],
    [
      "p2",
      "Leche entera",
      "Caja de 6 × 1 L",
      "Cafetería",
      "L",
      8,
      12,
      30,
      6,
      690,
      "s2",
      "milk",
    ],
    [
      "p3",
      "Pistacho siciliano",
      "Helado terminado · cubeta 5 kg",
      "Gelatería",
      "kg",
      3.2,
      5,
      10,
      5,
      6800,
      "s3",
      "ice",
    ],
    [
      "p4",
      "Chocolate 70 %",
      "Helado terminado · cubeta 5 kg",
      "Gelatería",
      "kg",
      7.5,
      4,
      10,
      5,
      4900,
      "s3",
      "ice",
    ],
    [
      "p5",
      "Vainilla de Madagascar",
      "Helado terminado · cubeta 5 kg",
      "Gelatería",
      "kg",
      6,
      4,
      10,
      5,
      4500,
      "s3",
      "ice",
    ],
    [
      "p6",
      "Vasos para llevar",
      "Paquete de 50 · 240 ml",
      "Envases",
      "ud",
      35,
      100,
      250,
      50,
      480,
      "s4",
      "cup",
    ],
    [
      "p7",
      "Bebida de avena",
      "Barista · caja de 6 × 1 L",
      "Cafetería",
      "L",
      12,
      6,
      24,
      6,
      1380,
      "s2",
      "milk",
    ],
    [
      "p8",
      "Tarta de queso",
      "Porciones terminadas · caja de 8",
      "Postres",
      "ud",
      5,
      8,
      16,
      8,
      2400,
      "s2",
      "cake",
    ],
    [
      "p9",
      "Conos artesanos",
      "Caja de 100 unidades",
      "Envases",
      "ud",
      140,
      80,
      200,
      100,
      1850,
      "s4",
      "ice",
    ],
    [
      "p10",
      "Nata para montar",
      "Caja de 6 × 1 L",
      "Postres",
      "L",
      9,
      6,
      18,
      6,
      2580,
      "s2",
      "milk",
    ],
  ];
  const products: Product[] = rows.map(
    ([
      id,
      name,
      detail,
      category,
      unit,
      stock,
      min,
      target,
      pack,
      price,
      supplier,
      icon,
    ]) => ({
      id,
      name,
      detail,
      category,
      unit,
      stock,
      min,
      target,
      pack,
      price,
      supplier,
      icon,
    }),
  );
  return {
    version: 1,
    revision: 0,
    business: "Gelato & Café",
    demo: true,
    products,
    suppliers: [
      {
        id: "s1",
        name: "Origen Coffee",
        initials: "OC",
        category: "Café de especialidad",
        delivery: "Martes y jueves",
        color: "sand",
      },
      {
        id: "s2",
        name: "Fresco Mercado",
        initials: "FM",
        category: "Lácteos y pastelería",
        delivery: "Lunes a viernes",
        color: "rose",
      },
      {
        id: "s3",
        name: "Gelato Italia",
        initials: "GI",
        category: "Helados artesanos",
        delivery: "Miércoles y viernes",
        color: "sage",
      },
      {
        id: "s4",
        name: "EcoPack",
        initials: "EP",
        category: "Envases y consumibles",
        delivery: "48–72 horas",
        color: "lavender",
      },
    ],
    processed: [],
    movements: [],
    cart: [],
    orders: [],
    messages: [
      {
        id: "welcome-message",
        supplier: "s2",
        text: "Buenos días. Esta semana la entrega del jueves pasa al viernes. Confírmanos si te viene bien.",
        kind: "delivery",
        priority: "important",
        reason: "Cambio de entrega: requiere revisión.",
        read: false,
        reviewed: false,
        at: new Date().toISOString(),
        simulated: true,
      },
    ],
    activity: [
      {
        id: randomUUID(),
        at: new Date().toISOString(),
        text: "Espacio de demostración creado. Los proveedores y precios son ficticios.",
      },
    ],
    photos: [],
  };
}
