$env:TEMP='D:\CARPETAPROYECTOS\APPGELATOSTOCK\work'
$env:TMP='D:\CARPETAPROYECTOS\APPGELATOSTOCK\work'
$env:PWTEST_DAEMON_SESSION_DIR='D:\CARPETAPROYECTOS\APPGELATOSTOCK\work\pw-daemon'
$env:PLAYWRIGHT_BROWSERS_PATH='D:\CARPETAPROYECTOS\APPGELATOSTOCK\work\browsers'
& 'D:\CARPETAPROYECTOS\APPGELATOSTOCK\node_modules\.bin\playwright-cli.cmd' @args
