// «Arte + gelato»: cultura del gelato para el chat de dudas. Texto propio, escrito a mano, sin
// generación automática. Cada línea es un párrafo que el chat puede citar tal cual. Donde la
// historia es tradición y no documento, se dice.
module.exports = `Gelato y helado: el gelato italiano lleva menos grasa (normalmente entre un 4 % y un 9 %, frente al 10 % o más del ice cream de tradición anglosajona), incorpora mucho menos aire al mantecar (un 20 %–35 % de aumento de volumen frente al 50 %–100 % del helado industrial) y se sirve algo menos frío, alrededor de −12 °C a −14 °C en vez de −18 °C. Por eso el gelato se percibe más denso, más cremoso y con el sabor más intenso, y se sirve con espátula en vez de cuchara de bola.
Gelato y sorbete: el sorbete (sorbetto) no lleva leche ni nata: es agua, azúcar y fruta; el gelato de crema parte de leche o nata. Un gelato de pistacho es una crema; un gelato de limón suele ser un sorbete. Ambos se mantecan y se sirven a la misma temperatura.
Historia, primeras raíces: mezclar nieve o hielo con miel, frutas y zumos es antiguo (se cuenta de Persia, de la China antigua y de la Roma imperial), pero eso son granizados, no gelato: sin leche y sin mantecar.
Historia, el Renacimiento: la tradición sitúa el gelato en la Florencia del siglo XVI. Se atribuye a Bernardo Buontalenti, arquitecto y escenógrafo de los Médici, una crema helada servida en banquetes de la corte hacia 1560; en Florencia todavía se vende un gelato «Buontalenti» en su honor. Es tradición más que documento firmado.
Historia, París: en 1686 el siciliano Francesco Procopio dei Coltelli abrió en París el Café Procope, donde los sorbetes y helados se vendían al público y no solo a la corte. De Sicilia también vienen la granita y la tradición de los gelatieri ambulantes.
Historia, la máquina: la técnica de congelar con hielo y sal (que baja el punto de congelación) es del siglo XVI–XVII; en 1843 Nancy Johnson patentó en Estados Unidos la heladera manual de manivela, y las mantecadoras eléctricas del siglo XX permitieron el gelato artesanal moderno con poco aire.
Mallorca: la isla tiene tradición heladera propia. Ca'n Joan de s'Aigo, en Palma, se remonta a 1700 y es famosa por el helado de almendra mallorquina (gelat d'ametlla) y por el chocolate con ensaimada; la almendra de Mallorca es una de las señas de identidad de sus helados.
Artello, arte + gelato: la idea es tratar cada sabor como una pieza: receta equilibrada, ingredientes con nombre y apellido y una presentación cuidada. El sabor de la casa, Mediterraneo, combina pistacho, rosa y azafrán: el pistacho aporta grasa y cuerpo, la rosa perfume y el azafrán color y un amargor fino.
Equilibrio de un gelato: un gelato de crema suele tener entre un 32 % y un 42 % de sólidos totales, entre un 16 % y un 22 % de azúcares, entre un 4 % y un 9 % de grasa y alrededor de un 8 %–11 % de sólidos lácteos no grasos; con más azúcar queda más blando y con más grasa más cremoso pero más pesado. Los sorbetes van más altos en azúcar (26 %–32 %) para no congelarse duros.
Maduración: dejar reposar la mezcla pasteurizada entre 4 y 12 horas a unos 4 °C hidrata las proteínas y estabilizantes y da un gelato más fino y estable; después se manteca y se abate rápido para que los cristales de hielo sean pequeños.
Pistacho: el más apreciado en heladería es el de Bronte, en la ladera del Etna (Sicilia), con denominación de origen protegida; su verde y su aroma marcan un gelato de pistacho «de verdad», sin colorantes.
Vitrina: el gelato artesanal se exhibe en cubetas (pozzetti, tapadas, lo conservan mejor) o en vitrina abierta; las montañas altísimas de colores brillantes suelen indicar aire y colorante, no calidad.`;
